import { ProjectStatus } from "@/API";

export const getProjectStatusIndex = (status: ProjectStatus): number => {
  const statusMap: Record<ProjectStatus, number> = {
    [ProjectStatus.AWAITING_ELECTRIC_BILL_REVIEW]: 0,
    [ProjectStatus.ELECTRIC_BILL_ISSUE_AWAITING_CUSTOMER_RE_UPLOAD]: 0,
    [ProjectStatus.ELECTRIC_BILL_REVIEWED_AWAITING_TRUE_DESIGN_PAYMENT]: 1,
    [ProjectStatus.TRUE_DESIGN_PAYMENT_ISSUE_AWAITING_RESOLUTION]: 1,
    [ProjectStatus.TRUE_DESIGN_PAYMENT_SUCCEEDED_AWAITING_TRUE_DESIGN_ORDER]: 1,
    [ProjectStatus.TRUE_DESIGN_ORDER_FAILED_AWAITING_RESOLUTION]: 1,
    [ProjectStatus.TRUE_DESIGN_ORDER_COMPLETED_AWAITING_FINAL_DESIGN_CREATION]: 1,
    [ProjectStatus.FINAL_DESIGN_FAILED_AWAITING_RESOLUTION]: 1,
    [ProjectStatus.FINAL_DESIGN_COMPLETE_AWAITING_CUSTOMER_APPROVAL]: 1,
    [ProjectStatus.CUSTOMER_REJECTED_FINAL_DESIGN_AWAITING_RESOLUTION]: 1,
    [ProjectStatus.CUSTOMER_APPROVED_FINAL_DESIGN_AWAITING_INSTALLER_AGREEMENT_SIGNATURE]: 2,
    [ProjectStatus.INSTALLER_AGREEMENT_SIGNATURE_OBTAINED_AWAITING_DEPOSIT]: 2,
    [ProjectStatus.DEPOSIT_UNSUCCESSFUL_AWAITING_RESOLUTION]: 2,
    [ProjectStatus.DEPOSIT_SUCCESSFUL_AWAITING_SITE_SURVEY_SCHEDULE]: 3,
    [ProjectStatus.SITE_SURVEY_SCHEDULED_AWAITING_SITE_VISIT]: 3,
    [ProjectStatus.SITE_VISITED_AWAITING_SITE_APPROVAL]: 3,
    [ProjectStatus.SITE_NOT_APPROVED_CHANGE_ORDER_REQUIRED]: 3,
    [ProjectStatus.CHANGE_ORDER_SUBMITTED_AWAITING_CUSTOMER_SIGNATURE]: 3,
    [ProjectStatus.CUSTOMER_SIGNATURE_OBTAINED_AWAITING_ENGINEERING_DOCS]: 3,
    [ProjectStatus.SITE_NOT_APPROVED_CANNOT_SERVICE]: 3,
    [ProjectStatus.SITE_APPROVED_AWAITING_ENGINEERING_DOCS]: 4,
    [ProjectStatus.ENGINEERING_DOCS_FINISHED_AWAITING_PERMITS]: 4,
    [ProjectStatus.PERMITS_NOT_OBTAINED_AWAITING_RESOLUTION]: 4,
    [ProjectStatus.PERMITS_OBTAINED_AWAITING_SECOND_PAYMENT]: 5,
    [ProjectStatus.SECOND_PAYMENT_UNSUCCESSFUL_AWAITING_RESOLUTION]: 5,
    [ProjectStatus.SECOND_PAYMENT_SUCCESSFUL_AWAITING_INSTALL_SCHEDULE]: 6,
    [ProjectStatus.INSTALL_SCHEDULED_AWAITING_INSTALL]: 6,
    [ProjectStatus.INSTALL_NOT_COMPLETED_AWAITING_RESOLUTION]: 6,
    [ProjectStatus.INSTALL_COMPLETED_AWAITING_UTILITY_APPROVAL]: 7,
    [ProjectStatus.UTILITY_APPROVAL_ISSUE_AWAITING_RESOLUTION]: 7,
    [ProjectStatus.UTILITY_APPROVED_AWAITING_SYSTEM_TURN_ON]: 7,
    [ProjectStatus.SYSTEM_NOT_TURNED_ON_AWAITING_RESOLUTION]: 7,
    [ProjectStatus.SYSTEM_TURNED_ON]: 7
  };
 
  return statusMap[status] ?? 0;
 };